src/main/java/org/yidu/novel/dto/BookcaseDTO.java
package org.yidu.novel.dto;

import java.util.Date;

import javax.servlet.http.HttpServletResponse;

import org.apache.commons.lang3.StringUtils;
import org.apache.struts2.ServletActionContext;
import org.yidu.novel.action.InfoAction;
import org.yidu.novel.action.ReaderAction;
import org.yidu.novel.constant.YiDuConfig;
import org.yidu.novel.constant.YiDuConstants;
import org.yidu.novel.entity.TBookcase;

/**
 * 
 * <p>
 * 书签DTO
 * </p>
 * Copyright(c) 2014 YiDu-Novel. All rights reserved.
 * 
 * @version 1.1.9
 * @author shinpa.you
 */
public class BookcaseDTO extends TBookcase {
    /**
     * 串行化版本统一标识符
     */
    private static final long serialVersionUID = 2193825089517868949L;
    /**
     * 最新章节编号
     */
    private Integer lastchapterno;
    /**
     * 最新章节名称
     */
    private String lastchapter;
    /**
     * 章节数
     */
    private Integer chapters;
    /**
     * 字数
     */
    private Integer size;
    /**
     * 全本标识
     */
    private Boolean fullflag;
    /**
     * 最后更新时间
     */
    private Date lastupdate;
    /**
     * 图片标识
     */
    private Integer imgflag;

    private String pinyin;

    /**
     * 获取最新章节编号
     * 
     * @return 最新章节编号
     */
    public Integer getLastchapterno() {
        return lastchapterno;
    }

    /**
     * 设定最新章节编号
     * 
     * @param lastchapterno
     *            最新章节编号
     */
    public void setLastchapterno(Integer lastchapterno) {
        this.lastchapterno = lastchapterno;
    }

    /**
     * 获取最新章节名
     * 
     * @return 最新章节名
     */
    public String getLastchapter() {
        return lastchapter;
    }

    /**
     * 设定最新章节名
     * 
     * @param lastchapter
     *            最新章节名
     */
    public void setLastchapter(String lastchapter) {
        this.lastchapter = lastchapter;
    }

    /**
     * 获取 chapters
     * 
     * @return chapters
     */
    public Integer getChapters() {
        return chapters;
    }

    /**
     * 
     * 设置chapters
     * 
     * 
     * @param chapters
     *            chapters
     */
    public void setChapters(Integer chapters) {
        this.chapters = chapters;
    }

    /**
     * 获取 size
     * 
     * @return size
     */
    public Integer getSize() {
        return size;
    }

    /**
     * 
     * 设置size
     * 
     * 
     * @param size
     *            size
     */
    public void setSize(Integer size) {
        this.size = size;
    }

    /**
     * 获取 fullflag
     * 
     * @return fullflag
     */
    public Boolean getFullflag() {
        return fullflag;
    }

    /**
     * 
     * 设置fullflag
     * 
     * 
     * @param fullflag
     *            fullflag
     */
    public void setFullflag(Boolean fullflag) {
        this.fullflag = fullflag;
    }

    /**
     * 获取 lastupdate
     * 
     * @return lastupdate
     */
    public Date getLastupdate() {
        return lastupdate;
    }

    /**
     * 
     * 设置lastupdate
     * 
     * 
     * @param lastupdate
     *            lastupdate
     */
    public void setLastupdate(Date lastupdate) {
        this.lastupdate = lastupdate;
    }

    /**
     * 获取 imgflag
     * 
     * @return imgflag
     */
    public Integer getImgflag() {
        return imgflag;
    }

    /**
     * 
     * 设置imgflag
     * 
     * 
     * @param imgflag
     *            imgflag
     */
    public void setImgflag(Integer imgflag) {
        this.imgflag = imgflag;
    }

    /**
     * 获取pinyin
     * 
     * @return pinyin
     */
    public String getPinyin() {
        return pinyin;
    }

    /**
     * 
     * 设置pinyin
     * 
     * 
     * @param pinyin
     *            pinyin
     */
    public void setPinyin(String pinyin) {
        this.pinyin = pinyin;
    }

    /**
     * 获得图片URL
     * 
     * @return 图片URL
     */
    public String getImgUrl() {
        String fileName = "";
        if (imgflag == null) {
            fileName = "nocover.jpg";
        } else {
            switch (imgflag) {
            case 1:
                fileName = getArticleno() + "s.jpg";
                break;
            case 2:
                fileName = getArticleno() + "s.gif";
                break;
            case 3:
                fileName = getArticleno() + "s.png";
                break;
            case 10:
                fileName = getArticleno() + "l.jpg";
                break;
            default:
                fileName = "nocover.jpg";
                break;
            }
        }
        String imgUrl = YiDuConstants.yiduConf.getString(YiDuConfig.RELATIVE_IAMGE_PATH) + "/";
        if (StringUtils.equals("nocover.jpg", fileName)) {
            imgUrl = imgUrl + fileName;
        } else {
            imgUrl = imgUrl + getArticleno() / YiDuConstants.SUB_DIR_ARTICLES + "/" + getArticleno() + "/" + fileName;
        }
        return imgUrl;
    }

    /**
     * 获取最新章节URL
     * 
     * @return 最新章节URL
     */
    public String getLastChapterUrl() {

        HttpServletResponse response = ServletActionContext.getResponse();
        String url = response.encodeURL(ReaderAction.URL + "?subdir=" + getSubdir() + "&articleno=" + getArticleno()
                + "&chapterno=" + getLastchapterno());

        if (YiDuConstants.yiduConf.getBoolean(YiDuConfig.ENABLE_PINYINURL, false)) {
            url = response.encodeURL(ReaderAction.URL + "?pinyin=" + getPinyin() + "&chapterno=" + getLastchapterno());
        }
        return url;
    }

    /**
     * 获取最新章节URL
     * 
     * @return 最新章节URL
     */
    public String getBookmarkUrl() {

        HttpServletResponse response = ServletActionContext.getResponse();
        String url = response.encodeURL(ReaderAction.URL + "?subdir=" + getSubdir() + "&articleno=" + getArticleno()
                + "&chapterno=" + getChapterno());

        if (YiDuConstants.yiduConf.getBoolean(YiDuConfig.ENABLE_PINYINURL, false)) {
            url = response.encodeURL(ReaderAction.URL + "?pinyin=" + getPinyin() + "&chapterno=" + getChapterno());
        }
        return url;
    }

    /**
     * 获取最新章节URL
     * 
     * @return 最新章节URL
     */
    public String getInfoUrl() {
        HttpServletResponse response = ServletActionContext.getResponse();
        String url = response.encodeURL(InfoAction.URL + "?subdir=" + getSubdir() + "&articleno=" + getArticleno());
        if (YiDuConstants.yiduConf.getBoolean(YiDuConfig.ENABLE_PINYINURL, false)) {
            url = response.encodeURL(InfoAction.URL + "?pinyin=" + getPinyin());
        }
        return url;
    }

}

src/main/java/org/yidu/novel/entity/TReview.java
package org.yidu.novel.entity;

import javax.servlet.http.HttpServletResponse;

import org.apache.struts2.ServletActionContext;
import org.yidu.novel.action.InfoAction;
import org.yidu.novel.action.UserInfoAction;
import org.yidu.novel.constant.YiDuConstants;
import org.yidu.novel.entity.base.BaseTReview;

public class TReview extends BaseTReview {
    private static final long serialVersionUID = 1L;

    /* [CONSTRUCTOR MARKER BEGIN] */
    public TReview() {
        super();
    }

    /**
     * Constructor for primary key
     */
    public TReview(int reviewno) {
        super(reviewno);
    }

    /* [CONSTRUCTOR MARKER END] */

    public Boolean getDeleteflag() {
        return isDeleteflag();
    }

    /**
     * 获得子目录 <br>
     * 默认是小说号/1000
     * 
     * @return 子目录
     */
    public Integer getSubdir() {
        return getArticleno() / YiDuConstants.SUB_DIR_ARTICLES;
    }

    /**
     * 获取用户信息URL
     * 
     * @return 用户信息URL
     */
    public String getUserInfoUrl() {
        HttpServletResponse response = ServletActionContext.getResponse();
        return response.encodeURL(UserInfoAction.URL + "?userno=" + getUserno());
    }

    /**
     * 获取小说介绍页URL
     * 
     * @return 小说介绍页URL
     */
    public String getInfoUrl() {
        HttpServletResponse response = ServletActionContext.getResponse();
        return response.encodeURL(InfoAction.URL + "?subdir=" + getSubdir() + "&articleno=" + getArticleno());
    }

}

src/main/java/org/yidu/novel/entity/TUser.java
package org.yidu.novel.entity;

import org.yidu.novel.entity.base.BaseTUser;

public class TUser extends BaseTUser {
    private static final long serialVersionUID = 1L;

    /* [CONSTRUCTOR MARKER BEGIN] */
	public TUser () {
		super();
	}

	/**
	 * Constructor for primary key
	 */
	public TUser (int userno) {
		super(userno);
	}

    /* [CONSTRUCTOR MARKER END] */

    public Boolean getDeleteflag() {
        return isDeleteflag();
    }
    
    public Boolean getActivedflag() {
        return isActivedflag();
    }


    // 为了Struts2的Json Result
    @Override
    public int getUserno() {
        return super.getUserno();
    }

    @Override
    public String getLoginid() {
        return super.getLoginid();
    }

    @Override
    public Short getType() {
        return super.getType();
    }

    @Override
    public String getOpenid() {
        return super.getOpenid();
    }

}

src/main/java/org/yidu/novel/action/ArticleListAction.java
package org.yidu.novel.action;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import org.apache.struts2.convention.annotation.Action;
import org.springframework.beans.BeanUtils;
import org.yidu.novel.action.base.AbstractPublicListBaseAction;
import org.yidu.novel.bean.ArticleSearchBean;
import org.yidu.novel.cache.ArticleCountManager;
import org.yidu.novel.cache.CacheManager;
import org.yidu.novel.constant.YiDuConfig;
import org.yidu.novel.constant.YiDuConstants;
import org.yidu.novel.entity.TArticle;
import org.yidu.novel.utils.Utils;

import com.google.gson.Gson;

/**
 * 
 * <p>
 * 小说列表Action
 * </p>
 * Copyright(c) 2013 YiDu-Novel. All rights reserved.
 * 
 * @version 1.1.9
 * @author shinpa.you
 */
@Action(value = "articleList")
public class ArticleListAction extends AbstractPublicListBaseAction {
    /**
     * 串行化版本统一标识符
     */
    private static final long serialVersionUID = -4215796997609788238L;

    /**
     * 功能名称。
     */
    public static final String NAME = "articleList";

    /**
     * 访问URL。
     */
    public static final String URL = NAMESPACE + "/" + NAME;

    /**
     * 小说种类
     */
    private Integer category;

    /**
     * 页号
     */
    private int page;

    /**
     * 作者
     */
    private String author;

    /**
     * 完本标志
     */
    private Boolean fullflag;
    /**
     * 标签
     */
    private String tag;

    /**
     * 小说列表
     */
    private List<TArticle> articleList = new ArrayList<TArticle>();

    /**
     * 全本的最新入库小说列表 TODO 区块对应
     */
    private List<TArticle> lastPostFullArticleList = new ArrayList<TArticle>();

    /**
     * 获取category
     * 
     * @return category
     */
    public Integer getCategory() {
        return category;
    }

    /**
     * 
     * 设置category
     * 
     * 
     * @param category
     *            category
     */
    public void setCategory(Integer category) {
        this.category = category;
    }

    /**
     * 获取 page
     * 
     * @return page
     */
    public int getPage() {
        return page ==0 ? 1 : page;
    }

    /**
     * 
     * 设置page
     * 
     * 
     * @param page
     *            page
     */
    public void setPage(int page) {
        this.page = page;
    }

    /**
     * 获取 author
     * 
     * @return author
     */
    public String getAuthor() {
        return author;
    }

    /**
     * 
     * 设置author
     * 
     * 
     * @param author
     *            author
     */
    public void setAuthor(String author) {
        this.author = author;
    }

    /**
     * 获取 fullflag
     * 
     * @return fullflag
     */
    public Boolean getFullflag() {
        return fullflag;
    }

    /**
     * 
     * 设置fullflag
     * 
     * 
     * @param fullflag
     *            fullflag
     */
    public void setFullflag(Boolean fullflag) {
        this.fullflag = fullflag;
    }

    public String getTag() {
        return tag;
    }

    public void setTag(String tag) {
        this.tag = tag;
    }

    /**
     * 获取 articleList
     * 
     * @return articleList
     */
    public List<TArticle> getArticleList() {
        return articleList;
    }

    /**
     * 
     * 设置articleList
     * 
     * 
     * @param articleList
     *            articleList
     */
    public void setArticleList(List<TArticle> articleList) {
        this.articleList = articleList;
    }

    public List<TArticle> getLastPostFullArticleList() {
        return lastPostFullArticleList;
    }

    public void setLastPostFullArticleList(List<TArticle> lastPostFullArticleList) {
        this.lastPostFullArticleList = lastPostFullArticleList;
    }

    @Override
    public String getTempName() {
        return "articleList";
    }
    
    /**
     * 获取排行榜名字的JSON数据
     * 
     * @return 排行榜名字的JSON数据
     */
    public String getTopNameJsonData() {
        Gson gson = new Gson();
        return gson.toJson(YiDuConstants.TOP_NAME_MAP, Map.class);
    }

    @Override
    protected void loadData() {
        logger.debug("loadData start.");

        ArticleSearchBean searchBean = new ArticleSearchBean();
        BeanUtils.copyProperties(this, searchBean);
        searchBean.setPageType(ArticleSearchBean.PageType.publicPage);

        pagination.setPageNumber(page == 0 ? 1 : page);
        pagination.setSortColumn(TArticle.PROP_LASTUPDATE);
        pagination.setSortOrder("DESC");

        int count = 0;
        if (YiDuConstants.yiduConf.getBoolean(YiDuConfig.ENABLE_CACHE_ARTICLE_COUNT, false)) {
            // 开启缓存件数的话
            if (Utils.isDefined(category)) {
                // 分类
                count = ArticleCountManager.getArticleCount(String.valueOf(category));
            } else if (Utils.isDefined(author)) {
                count = ArticleCountManager.getArticleCount(YiDuConstants.CacheCountType.AUTHOR);
            } else if (fullflag != null && fullflag) {
                count = ArticleCountManager.getArticleCount(YiDuConstants.CacheCountType.FULLFLAG);
            } else if (Utils.isDefined(tag)) {
                count = ArticleCountManager.getArticleCount(YiDuConstants.CacheCountType.TAG);
            } else {
                count = ArticleCountManager.getArticleCount(YiDuConstants.CacheCountType.ALL);
            }
        } else {
            Object countInfo = CacheManager.getObject(CacheManager.CacheKeyPrefix.CACHE_KEY_ARTICEL_LIST_COUNT_PREFIX,
                    searchBean);
            if (countInfo == null) {
                count = articleService.getCount(searchBean);
                CacheManager.putObject(CacheManager.CacheKeyPrefix.CACHE_KEY_ARTICEL_LIST_COUNT_PREFIX, searchBean,
                        count);
            } else {
                count = Integer.parseInt(countInfo.toString());
            }
        }
        // 总件数设置
        pagination.setPreperties(count);
        searchBean.setPagination(pagination);

        articleList = CacheManager.getObject(CacheManager.CacheKeyPrefix.CACHE_KEY_ARTICEL_LIST_PREFIX, searchBean);
        if (!Utils.isDefined(articleList)) {
            articleList = articleService.find(searchBean);
            CacheManager.putObject(CacheManager.CacheKeyPrefix.CACHE_KEY_ARTICEL_LIST_PREFIX, searchBean, articleList);
        }

        if (Utils.isDefined(fullflag) && fullflag) {
            lastPostFullArticleList = CacheManager.getObject(CacheManager.CacheKeyPrefix.CACHE_KEY_ARTICEL_LIST_PREFIX
                    + fullflag, searchBean);
            if (!Utils.isDefined(lastPostFullArticleList)) {
                searchBean.getPagination().setSortColumn(TArticle.PROP_POSTDATE);
                lastPostFullArticleList = articleService.find(searchBean);
                CacheManager.putObject(CacheManager.CacheKeyPrefix.CACHE_KEY_ARTICEL_LIST_PREFIX + fullflag,
                        searchBean, lastPostFullArticleList);
            }
        }

        logger.debug("normally end.");
    }

    @Override
    public int getPageType() {
        return YiDuConstants.Pagetype.PAGE_ARTICLE_LIST;
    }

    @Override
    protected String getBlockKey() {
        return CacheManager.CacheKeyPrefix.CACHE_KEY_CATEGORY_LIST_BLOCK;
    }

    @Override
    protected Short getBlockTarget() {
        return YiDuConstants.BlockTarget.ARTICLE_LIST;
    }
}

src/main/java/org/yidu/novel/action/BookcaseAction.java
package org.yidu.novel.action;

import org.yidu.novel.action.base.AbstractPublicBaseAction;
import org.yidu.novel.constant.YiDuConstants;

/**
 * 
 * <p>
 * 书架管理Action
 * </p>
 * Copyright(c) 2013 YiDu-Novel. All rights reserved.
 * 
 * @version 1.1.9
 * @author shinpa.you
 */
public class BookcaseAction extends AbstractPublicBaseAction {
    /**
     * 串行化版本统一标识符
     */
    private static final long serialVersionUID = 366181195078436796L;

    /**
     * 获得模版名字
     * 
     * @return 模版名字
     */
    @Override
    public String getTempName() {
        return "bookcase";
    }

    @Override
    public int getPageType() {
        return YiDuConstants.Pagetype.PAGE_BOOKCASE;
    }

    @Override
    protected void loadData() {
    }
}

src/main/webapp/themes/default/pc/user/articleList.ftl
<#include "usercommon.ftl"/>

<#macro titleContent>  
<title>我的小说|${getText("label.system.title")}</title>
<meta name="keywords" content="${getText("label.system.siteKeywords")}"/>
<meta name="description" content="${getText("label.system.siteDescription")}" />
</#macro>  

<#macro content>
<div class="layout grid-s160m0e190 channel-netnovel">
    <div class="col-main"><div class="main-wrap channel-netnovel-main">
    <section>
        <header class="netnovel-header">
            <h3>我的小说 &nbsp;&nbsp;- 您共有 ${articleList.size()}本小说。  &nbsp;&nbsp;<a href='${encodeURL("/user/articleEdit")}' ><font color=red>添加小说</font></a></h3>
        </header>
        <form action="" method="post" name="checkform" id="checkform" onSubmit="return check_confirm();">
            <table class="mygrid" width="100%" align="center" style="font-size:12px">
              <tbody>
              <tr align="center">
                    <th width="20%">小说名</th>
                    <th width="10%">小说类型</th>
                    <th width="45%">最新章节</th>
                    <th width="25%">操作</th>
              </tr>
              <#list articleList as article>
              <tr>
                    <td class="even">${article.articlename}</td>
                    <td class="odd">${article.categoryStr}</td>
                    <td class="odd"><#if article.lastchapter??>${article.lastchapter}</#if></td>
                    <td class="even" align="center">
                        <a href='${encodeURL("/user/articleEdit?articleno=${article.articleno?c}")}' >编辑</a>
                        <a href='${encodeURL("/user/articleEdit?articleno=${article.articleno?c}")}' >申请上架</a>
                        <a href='#' >评论管理</a>
                        <a href='${encodeURL("/user/chapterList?articleno=${article.articleno?c}")}'>章节管理</a>
                        <a href="javascript:if(confirm('确实要删除这本小说么？')) document.location='${encodeURL("/user/articleList!delete?articleno=${article.articleno?c}")}';">删除</a>
                    </td>
             </tr>
             </#list>
            </tbody>
          </table>
        </form>
    </section>
    </div>
</div>
<#if menuContent?exists>  
    <@menuContent/>  
</#if>
</#macro>

src/main/webapp/themes/default/pc/user/bookcase.ftl
<#include "usercommon.ftl"/>

<#macro titleContent>  
<title>我的书架|${getText("label.system.title")}</title>
<meta name="keywords" content="${getText("label.system.siteKeywords")}"/>
<meta name="description" content="${getText("label.system.siteDescription")}" />
</#macro>  

<#macro content>
<div class="layout grid-s160m0e190 channel-netnovel">
    <div class="col-main"><div class="main-wrap channel-netnovel-main">
    <section>
        <header class="netnovel-header">
            <h3>我的书架 &nbsp;&nbsp;- 您的书架可收藏 ${maxBookcaseNum} 本，已收藏${bookcaseNum} 本。</h3>
        </header>
        <form action="" method="post" name="checkform" id="checkform" onSubmit="return check_confirm();">
            <table class="mygrid" width="100%" align="center" style="font-size:12px">
              <tbody>
              <tr align="center">
                    <th width="5%">
                        <input type="checkbox" id="checkall" name="checkall" value="checkall" onclick="javascript: for (var i=0;i<this.form.elements.length;i++){ if (this.form.elements[i].name != 'checkkall') this.form.elements[i].checked = form.checkall.checked; }"></th>
                    <th width="21%">小说名</th>
                    <th width="30%">最新章节</th>
                    <th width="30%">书签</th>
                    <th width="7%">操作</th>
              </tr>
              <#list bookcaseList as bookcase>
              <tr>
                    <td class="odd" align="center">
                    <input type="checkbox" id="checkid[]" name="checkid[]" value="${bookcase.bookcaseno}">&nbsp;<span class="hottext"><#if bookcase.chapterno?? && bookcase.chapterno!=bookcase.lastchapterno>新</#if></span> </td>
                    <td class="even"><a href="${bookcase.infoUrl}" target="_blank">${bookcase.articlename}</a></td>
                    <td class="odd"><a href="${bookcase.lastChapterUrl}" target="_blank">${bookcase.lastchapter}</a>
                    </td>
                    <td class="even"><#if bookcase.chapterno??><a href="${bookcase.bookmarkUrl}" target="_blank">${bookcase.chaptername}</a></#if></td>
                    <td class="even" align="center"><a href="javascript:if(confirm('确实要将本书移出书架么？')) document.location='${encodeURL("/user/bookcase!delete?bookcaseno=${bookcase.bookcaseno?c}")}';">移除</a></td>
             </tr>
             </#list>
            </tbody>
          </table>
        </form>
    </section>
    </div>
</div>
<#if menuContent?exists>  
    <@menuContent/>  
</#if>
</#macro>

src/main/webapp/themes/default/pc/user/message.ftl
<#include "usercommon.ftl"/>

<#macro titleContent>  
<title>我的消息|${getText("label.system.title")}</title>
<meta name="keywords" content="${getText("label.system.siteKeywords")}"/>
<meta name="description" content="${getText("label.system.siteDescription")}" />
</#macro>  

<#macro content>
<div class="layout grid-s160m0e190 channel-netnovel">
    <div class="col-main"><div class="main-wrap channel-netnovel-main">
    <section>
        <header class="netnovel-header">
            <h3>我的消息 &nbsp;&nbsp;- 您共有 ${messageList.size()}条消息。</h3>
        </header>
        <form action="" method="post" name="checkform" id="checkform" onSubmit="return check_confirm();">
            <table class="mygrid" width="100%" align="center" style="font-size:12px">
              <tbody>
              <tr align="center">
                    <th width="5%">
                        <input type="checkbox" id="checkall" name="checkall" value="checkall" onclick="javascript: for (var i=0;i<this.form.elements.length;i++){ if (this.form.elements[i].name != 'checkkall') this.form.elements[i].checked = form.checkall.checked; }"></th>
                    <th width="21%">来自用户</th>
                    <th width="30%">标题</th>
                    <th width="30%">内容概要</th>
                    <th width="7%">操作</th>
              </tr>
              <#list messageList as message>
              <tr>
                    <td class="odd" align="center">
                    <input type="checkbox" id="checkid[]" name="checkid[]" value="${message.messageno?c}">&nbsp;<span class="hottext"><#if message.isread?? && message.isread>未读</#if></span> </td>
                    <td class="even">${message.loginid}</td>
                    <td class="odd">${message.title}</td>
                    <td class="even">${message.content}</td>
                    <td class="even" align="center"><a href="javascript:if(confirm('确实要删除这条消息么？')) document.location='${encodeURL("/user/message!delete?messageno=${message.messageno?c}")}';">移除</a></td>
             </tr>
             </#list>
            </tbody>
          </table>
        </form>
    </section>
    </div>
</div>
<#if menuContent?exists>  
    <@menuContent/>  
</#if>
</#macro>

src/main/webapp/themes/default/pc/user/messageEdit.ftl
<#include "usercommon.ftl"/>

<#macro titleContent>  
<title>发送消息|${getText("label.system.title")}</title>
<meta name="keywords" content="${getText("label.system.siteKeywords")}"/>
<meta name="description" content="${getText("label.system.siteDescription")}" />
</#macro>  

<#macro content>
<@s.form action="messageEdit" method="post" validate="true">
    <center>
        <span id="ErrorList"><@s.fielderror /> <@s.actionerror /></span>
    </center>
    <table class="grid" align="center" width="400">
      <caption>
        发送消息给管理员
      </caption>
      <tbody>
        <tr>
          <td sytle="text-align: right; padding-left: 20px;" class="odd" width="25%">标&nbsp;&nbsp;题:</td>
          <td class="even">
                <@s.textfield name="title" id = "title" cssStyle="width:150px; height:20px;" maxlength="32"/>
          </td>
        </tr>
        <tr>
          <td class="odd" width="25%">内&nbsp;&nbsp;容:</td>
          <td class="even">
            <@s.textarea name="content" cssStyle="160px;"  cssClass="text"  cols="74" rows="8"/>
          </td>
        </tr>
        <tr>
          <td class="odd" width="25%">&nbsp;
          </td>
          <td class="even">
              <@s.submit method="add" cssClass="submit" name="submit" theme="simple" cssStyle="cursor:pointer;" value=" 提 交 "/>
          </td>
        </tr>
      </tbody>
    </table>
</@s.form>
</#macro>

src/main/webapp/themes/default/pc/user/subscribe.ftl
<#include "usercommon.ftl"/>

<#macro titleContent>  
<title>我的订阅|${getText("label.system.title")}</title>
<meta name="keywords" content="${getText("label.system.siteKeywords")}"/>
<meta name="description" content="${getText("label.system.siteDescription")}" />
</#macro>  

<#macro content>
<div class="layout grid-s160m0e190 channel-netnovel">
    <div class="col-main"><div class="main-wrap channel-netnovel-main">
    <section>
        <header class="netnovel-headersubscribe ">
            <h3>我的订阅 &nbsp;&nbsp;- 您最大可以订阅  ${maxSubscribeNum} 本小说，现已订阅 ${subscribeNum} 本。<br>
            <span style="color:red">您订阅的小说如果更新了，我们会通过邮件的方式通知您，切记设置好邮件信息，否则无法使用该功能！</span></h3>
        </header>
        <form action="" method="post" name="checkform" id="checkform" onSubmit="return check_confirm();">
            <table class="mygrid" width="100%" align="center" style="font-size:12px">
              <tbody>
              <tr align="center">
                    <th width="10%">小说编号</th>
                    <th width="30%">小说名</th>
                    <th width="40%">最新章节</th>
                    <th width="20%">操作</th>
              </tr>
              <#list subscribeList as subscribe>
              <tr>
                    <td class="even">${subscribe.articleno?c}</td>
                    <td class="odd"><a href="${subscribe.url}" target="_blank">${subscribe.articlename}</a></td>
                    <td class="even"><a href="${subscribe.lastChapterUrl}" target="_blank">${subscribe.lastchapter}</a></td>
                    <td class="even" align="center"><a href="javascript:if(confirm('确实要取消订阅本书？')) document.location='${encodeURL("/user/subscribe!delete?subscribeno=${subscribe.subscribeno?c}")}';">移除</a></td>
             </tr>
             </#list>
            </tbody>
          </table>
        </form>
    </section>
    </div>
</div>
<#if menuContent?exists>  
    <@menuContent/>  
</#if>
</#macro>