src/main/java/org/yidu/novel/dto/BookcaseDTO.java
package org.yidu.novel.dto;

import java.util.Date;

import javax.servlet.http.HttpServletResponse;

import org.apache.commons.lang3.StringUtils;
import org.apache.struts2.ServletActionContext;
import org.yidu.novel.action.InfoAction;
import org.yidu.novel.action.ReaderAction;
import org.yidu.novel.constant.YiDuConfig;
import org.yidu.novel.constant.YiDuConstants;
import org.yidu.novel.entity.TBookcase;

/**
 * 
 * <p>
 * 书签DTO
 * </p>
 * Copyright(c) 2014 YiDu-Novel. All rights reserved.
 * 
 * @version 1.1.9
 * @author shinpa.you
 */
public class BookcaseDTO extends TBookcase {
    /**
     * 串行化版本统一标识符
     */
    private static final long serialVersionUID = 2193825089517868949L;
    /**
     * 最新章节编号
     */
    private Integer lastchapterno;
    /**
     * 最新章节名称
     */
    private String lastchapter;
    /**
     * 章节数
     */
    private Integer chapters;
    /**
     * 字数
     */
    private Integer size;
    /**
     * 全本标识
     */
    private Boolean fullflag;
    /**
     * 最后更新时间
     */
    private Date lastupdate;
    /**
     * 图片标识
     */
    private Integer imgflag;

    private String pinyin;

    /**
     * 获取最新章节编号
     * 
     * @return 最新章节编号
     */
    public Integer getLastchapterno() {
        return lastchapterno;
    }

    /**
     * 设定最新章节编号
     * 
     * @param lastchapterno
     *            最新章节编号
     */
    public void setLastchapterno(Integer lastchapterno) {
        this.lastchapterno = lastchapterno;
    }

    /**
     * 获取最新章节名
     * 
     * @return 最新章节名
     */
    public String getLastchapter() {
        return lastchapter;
    }

    /**
     * 设定最新章节名
     * 
     * @param lastchapter
     *            最新章节名
     */
    public void setLastchapter(String lastchapter) {
        this.lastchapter = lastchapter;
    }

    /**
     * 获取 chapters
     * 
     * @return chapters
     */
    public Integer getChapters() {
        return chapters;
    }

    /**
     * 
     * 设置chapters
     * 
     * 
     * @param chapters
     *            chapters
     */
    public void setChapters(Integer chapters) {
        this.chapters = chapters;
    }

    /**
     * 获取 size
     * 
     * @return size
     */
    public Integer getSize() {
        return size;
    }

    /**
     * 
     * 设置size
     * 
     * 
     * @param size
     *            size
     */
    public void setSize(Integer size) {
        this.size = size;
    }

    /**
     * 获取 fullflag
     * 
     * @return fullflag
     */
    public Boolean getFullflag() {
        return fullflag;
    }

    /**
     * 
     * 设置fullflag
     * 
     * 
     * @param fullflag
     *            fullflag
     */
    public void setFullflag(Boolean fullflag) {
        this.fullflag = fullflag;
    }

    /**
     * 获取 lastupdate
     * 
     * @return lastupdate
     */
    public Date getLastupdate() {
        return lastupdate;
    }

    /**
     * 
     * 设置lastupdate
     * 
     * 
     * @param lastupdate
     *            lastupdate
     */
    public void setLastupdate(Date lastupdate) {
        this.lastupdate = lastupdate;
    }

    /**
     * 获取 imgflag
     * 
     * @return imgflag
     */
    public Integer getImgflag() {
        return imgflag;
    }

    /**
     * 
     * 设置imgflag
     * 
     * 
     * @param imgflag
     *            imgflag
     */
    public void setImgflag(Integer imgflag) {
        this.imgflag = imgflag;
    }

    /**
     * 获取pinyin
     * 
     * @return pinyin
     */
    public String getPinyin() {
        return pinyin;
    }

    /**
     * 
     * 设置pinyin
     * 
     * 
     * @param pinyin
     *            pinyin
     */
    public void setPinyin(String pinyin) {
        this.pinyin = pinyin;
    }

    /**
     * 获得图片URL
     * 
     * @return 图片URL
     */
    public String getImgUrl() {
        String fileName = "";
        if (imgflag == null) {
            fileName = "nocover.jpg";
        } else {
            switch (imgflag) {
            case 1:
                fileName = getArticleno() + "s.jpg";
                break;
            case 2:
                fileName = getArticleno() + "s.gif";
                break;
            case 3:
                fileName = getArticleno() + "s.png";
                break;
            case 10:
                fileName = getArticleno() + "l.jpg";
                break;
            default:
                fileName = "nocover.jpg";
                break;
            }
        }
        String imgUrl = YiDuConstants.yiduConf.getString(YiDuConfig.RELATIVE_IAMGE_PATH) + "/";
        if (StringUtils.equals("nocover.jpg", fileName)) {
            imgUrl = imgUrl + fileName;
        } else {
            imgUrl = imgUrl + getArticleno() / YiDuConstants.SUB_DIR_ARTICLES + "/" + getArticleno() + "/" + fileName;
        }
        return imgUrl;
    }

    /**
     * 获取最新章节URL
     * 
     * @return 最新章节URL
     */
    public String getLastChapterUrl() {

        HttpServletResponse response = ServletActionContext.getResponse();
        String url = response.encodeURL(ReaderAction.URL + "?subdir=" + getSubdir() + "&articleno=" + getArticleno()
                + "&chapterno=" + getLastchapterno());

        if (YiDuConstants.yiduConf.getBoolean(YiDuConfig.ENABLE_PINYINURL, false)) {
            url = response.encodeURL(ReaderAction.URL + "?pinyin=" + getPinyin() + "&chapterno=" + getLastchapterno());
        }
        return url;
    }

    /**
     * 获取最新章节URL
     * 
     * @return 最新章节URL
     */
    public String getBookmarkUrl() {

        HttpServletResponse response = ServletActionContext.getResponse();
        String url = response.encodeURL(ReaderAction.URL + "?subdir=" + getSubdir() + "&articleno=" + getArticleno()
                + "&chapterno=" + getChapterno());

        if (YiDuConstants.yiduConf.getBoolean(YiDuConfig.ENABLE_PINYINURL, false)) {
            url = response.encodeURL(ReaderAction.URL + "?pinyin=" + getPinyin() + "&chapterno=" + getChapterno());
        }
        return url;
    }

    /**
     * 获取最新章节URL
     * 
     * @return 最新章节URL
     */
    public String getInfoUrl() {
        HttpServletResponse response = ServletActionContext.getResponse();
        String url = response.encodeURL(InfoAction.URL + "?subdir=" + getSubdir() + "&articleno=" + getArticleno());
        if (YiDuConstants.yiduConf.getBoolean(YiDuConfig.ENABLE_PINYINURL, false)) {
            url = response.encodeURL(InfoAction.URL + "?pinyin=" + getPinyin());
        }
        return url;
    }

}

src/main/java/org/yidu/novel/dto/ChapterDTO.java
package org.yidu.novel.dto;

import javax.servlet.http.HttpServletResponse;

import org.apache.commons.lang3.StringUtils;
import org.apache.struts2.ServletActionContext;
import org.yidu.novel.action.ChapterListAction;
import org.yidu.novel.action.InfoAction;
import org.yidu.novel.action.ReaderAction;
import org.yidu.novel.constant.YiDuConfig;
import org.yidu.novel.constant.YiDuConstants;
import org.yidu.novel.entity.TChapter;

/**
 * 
 * <p>
 * 章节DTO
 * </p>
 * Copyright(c) 2014 YiDu-Novel. All rights reserved.
 * 
 * @version 1.1.9
 * @author shinpa.you
 */
public class ChapterDTO extends TChapter {
    /**
     * 串行化版本统一标识符
     */
    private static final long serialVersionUID = -9171385880720383954L;
    /**
     * 下一章章节编号
     */
    private int nextChapterno;
    /**
     * 上一章章节编号
     */
    private int preChapterno;
    /**
     * 章节内容
     */
    private String content;

    /**
     * 拼音
     */
    private String pinyin;

    /**
     * 获取 nextChapterno
     * 
     * @return nextChapterno
     */
    public int getNextChapterno() {
        return nextChapterno;
    }

    /**
     * 
     * 设置nextChapterno
     * 
     * 
     * @param nextChapterno
     *            nextChapterno
     */
    public void setNextChapterno(int nextChapterno) {
        this.nextChapterno = nextChapterno;
    }

    /**
     * 获取 preChapterno
     * 
     * @return preChapterno
     */
    public int getPreChapterno() {
        return preChapterno;
    }

    /**
     * 
     * 设置preChapterno
     * 
     * 
     * @param preChapterno
     *            preChapterno
     */
    public void setPreChapterno(int preChapterno) {
        this.preChapterno = preChapterno;
    }

    /**
     * 获取pinyin
     * 
     * @return pinyin
     */
    public String getPinyin() {
        return pinyin;
    }

    /**
     * 
     * 设置pinyin
     * 
     * 
     * @param pinyin
     *            pinyin
     */
    public void setPinyin(String pinyin) {
        this.pinyin = pinyin;
    }

    /**
     * 获取 content
     * 
     * @return content
     */
    public String getContent() {
        String keywords = YiDuConstants.yiduConf.getString(YiDuConfig.FILTER_KEYWORD);
        String[] keywordArr = StringUtils.split(keywords, "#");
        for (String string : keywordArr) {
            content = content.replaceAll(string, "");
        }
        return content;
    }

    public String getEsccapeContent() {
        String escapeContent = StringUtils.replace(this.getContent(), "<", "&lt;");
        escapeContent = StringUtils.replace(escapeContent, ">", "&gt;");
        return escapeContent;
    }

    public String getReplacedContent() {
        String keywords = YiDuConstants.yiduConf.getString("filterKeyWord");
        String[] keywordArr = StringUtils.split(keywords, ",");
        String replaced = getContent();
        for (String string : keywordArr) {
            replaced = replaced.replaceAll(string, "");
        }
        return replaced;
    }

    /**
     * 
     * 设置content
     * 
     * 
     * @param content
     *            content
     */
    public void setContent(String content) {
        this.content = (content == null ? "" : content);
    }

    /**
     * 获取章节列表URL
     * 
     * @return 分类列表URL
     */
    public String getUrl() {
        HttpServletResponse response = ServletActionContext.getResponse();
        String url = response.encodeURL(ReaderAction.URL + "?subdir=" + getSubdir() + "&articleno=" + getArticleno()
                + "&chapterno=" + getChapterno());
        if (YiDuConstants.yiduConf.getBoolean(YiDuConfig.ENABLE_PINYINURL, false)) {
            url = response.encodeURL(ReaderAction.URL + "?pinyin=" + pinyin + "&chapterno=" + getChapterno());
        }
        return url;
    }

    /**
     * 获取章节列表URL
     * 
     * @return 分类列表URL
     */
    public String getChapterListUrl() {
        HttpServletResponse response = ServletActionContext.getResponse();
        String url = response.encodeURL(ChapterListAction.URL + "?subdir=" + getSubdir() + "&articleno="
                + getArticleno());
        if (YiDuConstants.yiduConf.getBoolean(YiDuConfig.ENABLE_PINYINURL, false)) {
            url = response.encodeURL(ChapterListAction.URL + "?pinyin=" + pinyin);
        }
        return url;
    }

    /**
     * 获取下一章章节URL
     * 
     * @return 下一章章节URL
     */

    public String getNextChapterUrl() {
        HttpServletResponse response = ServletActionContext.getResponse();
        if (getNextChapterno() != 0) {
            String url = response.encodeURL(ReaderAction.URL + "?subdir=" + getSubdir() + "&articleno="
                    + getArticleno() + "&chapterno=" + getNextChapterno());

            if (YiDuConstants.yiduConf.getBoolean(YiDuConfig.ENABLE_PINYINURL, false)) {
                url = response.encodeURL(ReaderAction.URL + "?pinyin=" + pinyin + "&chapterno=" + getNextChapterno());
            }
            return url;
        } else {
            if (YiDuConstants.yiduConf.getBoolean(YiDuConfig.ENABLE_CHAPTER_INDEX_PAGE, false)) {
                return getChapterListUrl();
            } else {
                String url = getInfoUrl();
                if (YiDuConstants.yiduConf.getBoolean(YiDuConfig.ENABLE_PINYINURL, false)) {
                    if(YiDuConstants.yiduConf.getBoolean(YiDuConfig.ENABLE_CHAPTER_INDEX_PAGE, false)){
                        url = response.encodeURL(ChapterListAction.URL + "?pinyin=" + pinyin);
                    }else{
                        url = response.encodeURL(InfoAction.URL + "?pinyin=" + pinyin);
                    }
                }
                return url;
            }
        }
    }

    /**
     * 获取下一章章节URL
     * 
     * @return 上一章章节URL
     */
    public String getPreChapterUrl() {
        HttpServletResponse response = ServletActionContext.getResponse();
        if (getPreChapterno() != 0) {
            String url = response.encodeURL(ReaderAction.URL + "?subdir=" + getSubdir() + "&articleno="
                    + getArticleno() + "&chapterno=" + getPreChapterno());

            if (YiDuConstants.yiduConf.getBoolean(YiDuConfig.ENABLE_PINYINURL, false)) {
                url = response.encodeURL(ReaderAction.URL + "?pinyin=" + pinyin + "&chapterno=" + getPreChapterno());
            }
            return url;

        } else {
            if (YiDuConstants.yiduConf.getBoolean(YiDuConfig.ENABLE_CHAPTER_INDEX_PAGE, false)) {
                return getChapterListUrl();
            } else {
                String url = getInfoUrl();
                if(YiDuConstants.yiduConf.getBoolean(YiDuConfig.ENABLE_CHAPTER_INDEX_PAGE, false)){
                    url = response.encodeURL(ChapterListAction.URL + "?pinyin=" + pinyin);
                }else{
                    url = response.encodeURL(InfoAction.URL + "?pinyin=" + pinyin);
                }
                return url;
            }
        }
    }

    /**
     * 获取下一章章节URL
     * 
     * @return 下一章章节URL
     */

    public String getNextChapterThumbnailUrl() {
        HttpServletResponse response = ServletActionContext.getResponse();
        return response.encodeURL(ReaderAction.URL + "?chapterno=" + getNextChapterno());
    }

    /**
     * 获取下一章章节URL
     * 
     * @return 上一章章节URL
     */
    public String getPreChapterThumbnailUrl() {
        HttpServletResponse response = ServletActionContext.getResponse();
        return response.encodeURL(ReaderAction.URL + "?chapterno=" + getPreChapterno());
    }

}

src/main/java/org/yidu/novel/action/SiteMapAction.java
package org.yidu.novel.action;

import java.util.ArrayList;
import java.util.List;

import org.apache.struts2.convention.annotation.Action;
import org.yidu.novel.action.base.AbstractPublicListBaseAction;
import org.yidu.novel.bean.ArticleSearchBean;
import org.yidu.novel.entity.TArticle;

/**
 * 
 * <p>
 * 网站地图Action
 * </p>
 * Copyright(c) 2013 YiDu-Novel. All rights reserved.
 * 
 * @version 1.1.9
 * @author shinpa.you
 */
@Action(value = "siteMap")
public class SiteMapAction extends AbstractPublicListBaseAction {
    /**
     * 串行化版本统一标识符
     */
    private static final long serialVersionUID = -3069730816500421029L;

    /**
     * 功能名称。
     */
    public static final String NAME = "siteMap";
    /**
     * URL。
     */
    public static final String URL = NAMESPACE + "/" + NAME;
    /**
     * 小说列表
     */
    private List<TArticle> articleList = new ArrayList<TArticle>();

    /**
     * 获取 articleList
     * 
     * @return articleList
     */
    public List<TArticle> getArticleList() {
        return articleList;
    }

    /**
     * 
     * 设置articleList
     * 
     * 
     * @param articleList
     *            articleList
     */
    public void setArticleList(List<TArticle> articleList) {
        this.articleList = articleList;
    }

    @Override
    public int getPageType() {
        return 0;
    }

    @Override
    public String getTempName() {
        return "siteMap";
    }

    @Override
    protected void loadData() {
        articleList = articleService.find(new ArticleSearchBean());
    }

}

src/main/webapp/themes/default/pc/reader.ftl
<#include "common.ftl"/>
<#macro titleContent>  
<title>${chapter.articlename}-${chapter.chaptername}</title>
<meta name="keywords" content="${chapter.chaptername},${chapter.articlename}最新章节,${chapter.articlename}TXT下载,${chapter.articlename}无广告,${getText("label.system.name")}" />
<meta name="description" content="${getText("label.system.siteDescription")}" />
</#macro>  
<#macro customizeimport>  
<link rel="stylesheet" type="text/css" href="${contextPath}/themes/${themeName}/pc/css/readtools.css" />
</#macro>

<#macro content>
<div class="mainnav">
        <div class="main-index" id="direct">
            <span class="r mr10">
                <form action="${contextPath}/search" method="get" >
                    搜小说：<input type="text" name="key" value="" />
                    <button type="submit" >搜</button>
                </form>
            </span>
    位置：&nbsp; > &nbsp; <a href="${contextPath}/" class="c009900">${getText("label.system.name")}</a> > 
    <a href="${article.url}" class="article_title">${chapter.articlename}</a>  > 
    <#if enableChapterIndexPage><a href="${article.chapterListUrl}" class="article_title">${chapter.articlename}章节目录</a> > </#if>
    ${chapter.chaptername}</div>
    <section class="main b-detail" id="directs">
        <div class="bookInfo">
            <h1>
                <span class="r"></span>
                <em class="l">《${chapter.articlename}》</em>
                <strong class="l jieqi_title">${chapter.chaptername}</strong>
                <a href="javascript:return false;" articleno="${article.articleno?c}" chapterno="${chapter.chapterno?c}"  id="addBookcaseButton" title="加入书签" class="l" rel="nofollow">加入书签</a>
                <a href="javascript:return false;" articleno="${article.articleno?c}"  id="voteButton"  title="推荐本书" class="l" rel="nofollow">推荐本书</a>
                <a href="javascript:return false;" articleno="${article.articleno?c}"  id="addSubscribeButton" title="订阅本书" class="l" rel="nofollow">订阅本书</a>
                <a href="/user/messageEdit?title=${article.articlename}-章节错误&content= 关于《${article.articlename}》举报原因如下，错误章节： ${chapter.chaptername}  "  class="l" target="_blank" rel="nofollow">内容报错</a>
                <a href="/user/messageEdit?title=${article.articlename}-更新太慢啦!&content=${article.articlename} 更新太慢了,请加快速度,别的网站都有最新章节了.(请您最好告诉我们现在有哪个网站更新速度比我们快，以便使我们知道进度落后的状况) 以下网站比${siteName}更新的快:  "  class="l" target="_blank" rel="nofollow">更新慢了</a>
                <div class="clear"></div>
            </h1>
            <div class="toolbar">
            <ul>
                <li>
                    <span class="fl">背景：</span>
                    <div class="fl">
                        <input id="bg1" onclick="setBG('#dcecf5')" type="button" class="setBG" />
                        <input id="bg2" onclick="setBG('#e1ffe6')" type="button" class="setBG" />
                        <input id="bg3" onclick="setBG('#edf6d0')" type="button" class="setBG" />
                        <input id="bg4" onclick="setBG('#eae8f7')" type="button" class="setBG" />
                        <input id="bg5" onclick="setBG('#f5f1e7')" type="button" class="setBG" />
                        <input id="bg6" onclick="setBG('#ebf4ef')" type="button" class="setBG" />
                        <input id="bg7" onclick="setBG('#FFFFFF')" type="button" class="setBG" />
                    </div>
                </li>
                <li>
                    <span class="fl">字体大小：</span>
                    <div class="fl">
                        <select onchange="setFontSize(this.value);" id="bcolor" name="bcolor">
                        <option value="#E9FAFF">大小</option>
                        <option value="14pt">默认</option><option value="10pt">10pt</option>
                        <option value="12pt">12pt</option><option value="14pt">14pt</option>
                        <option value="16pt">16pt</option><option value="18pt">18pt</option>
                        <option value="20pt">20pt</option><option value="22pt">22pt</option>
                        <option value="25pt">25pt</option><option value="30pt">30pt</option></select>
                    </div>    
                </li>
                <li>
                    <span class="fl">字体颜色：</span>
                    <div class="fl">
                        <select onchange="setFontColor(this.value)" id="txtcolor" name="txtcolor">
                            <option value="#000000">黑色</option>
                            <option value="#ff0000">红色</option>
                            <option value="#006600">绿色</option>
                            <option value="#0000ff">蓝色</option>
                            <option value="#660000">棕色</option>
                        </select>
                    </div>
                </li>
                <li id="sudu">
                    <span class="fl">滚动速度：</span>
                    <a id="sudu50" href="javascript:setSpeed(50);" rel="nofollow">快</a>
                    <a id="sudu100" href="javascript:setSpeed(100);" class="this" rel="nofollow">中</a>
                    <a id="sudu150" href="javascript:setSpeed(150);" rel="nofollow">慢</a>
                </li>
            </ul>
        </div>
        <div id="reader_ad_01"></div>
        <div class="mainContenr"   id="content">
            <#if chapter.content??>${chapter.content}</#if>
        </div>
        <div id="reader_ad_02"></div>
        <div class="backs">
            <a href="${chapter.preChapterUrl}" class="pre">上一章</a>
            <a href="<#if enableChapterIndexPage>${article.chapterListUrl}<#else>${article.url}</#if>" class="backfor">返回目录</a>
            <a href="${chapter.nextChapterUrl}" class="next">下一章</a>
            <p>小提示： 按←键返回上一页，按→键进入上一页,您还可以
                 <a href="${encodeURL("/user/bookcase!add?articleno=${chapter.articleno?c}&chapterno=${chapter.chapterno?c}")}" title="加入书签"  target="_blank">加入书签</a>
            </p></div>
        <div id="reader_ad_03"></div>
        </div>
       </section>
       <div class="attention">
            <em>阅读提示：</em><br/>
            1、本站会员登录后，将免费体会到最顺畅的阅读方式[<em>最少广告</em>]。<br/>
            2、<em>注册本站会员</em>，将《<a href="${article.url}" class="article_title"><em>${chapter.articlename}</em></a>》加入书架，可以通过书架更快的了解更新信息。<br/>
            3、免费小说《<a href="${article.url}" class="article_title"><em>${chapter.articlename}</em></a>》 ${chapter.chaptername}所描述的内容只是作者个人观点，与本站的立场无关，本站只为广大用户提供阅读平台。
        </div>
        
     <div class="navTab">
        <ul>
            <li onmouseover="replaces(1,2)" id="for1" class="select"><a href="#">站长推荐</a></li>
            <li onmouseover="replaces(2,2)" id="for2" class ><a href="#">猜你喜欢</a></li>
        </ul>
    </div>

    <div class="tabMain">
        <#if blocks.reader_recommand_list ?? > 
        <ul id="content1">
            <#list blocks.reader_recommand_list as article>
            <li><a href="${article.url}" title="${article.articlename}"><img src="${article.imgUrl}" width="111px;" height="146px;" alt="${article.articlename}"></a>
            <#if article.fullflag>
                <img src="${contextPath}/themes/${themeName}/pc/images/only.png" class="topss png_bg" alt="完本图标">
            <#else>
                <img src="${contextPath}/themes/${themeName}/pc/images/only2.png" class="topss png_bg"  alt="连载中图标">
            </#if>
            <a href="${article.url}">${article.articlename}</a></li>
            </#list>
        </ul>
        </#if>
        <#if blocks.reader_random_recommand_list ?? > 
        <ul id="content2" style="display:none;">
            <#list blocks.reader_random_recommand_list as article>
           <li><a href="${article.url}" title="${article.articlename}"><img src="${article.imgUrl}" width="111px;" height="146px;" alt="${article.articlename}"></a>
            <#if article.fullflag>
                <img src="${contextPath}/themes/${themeName}/pc/images/only.png" class="topss png_bg" alt="完本图标">
            <#else>
                <img src="${contextPath}/themes/${themeName}/pc/images/only2.png" class="topss png_bg"  alt="连载中图标">
            </#if>
            <a href="${article.url}">${article.articlename}</a></li>
            </#list>
        </ul>
        </#if>
    </div>
    </div>
</div>
<div id="reader_ad_04"></div>
</#macro>

<#macro customizeJs>
<script type="text/javascript" src="${contextPath}/themes/${themeName}/pc/js/tools.js"></script>
<script type="text/javascript">
    <!--
        var preview_page = "${chapter.preChapterUrl}";
        var next_page = "${chapter.nextChapterUrl}";
        var index_page = '<#if enableChapterIndexPage>${article.chapterListUrl}<#else>${article.url}</#if>';
        var readHistoryObject = new Object();
        readHistoryObject.chapterno = ${chapter.chapterno?c};
        readHistoryObject.articleno = ${chapter.articleno?c};
        readHistoryObject.chaptername = "${chapter.chaptername}";
        readHistoryObject.articlename = "${chapter.articlename}";
        readHistoryObject.infoUrl="${article.url}";
        readHistoryObject.chapterUrl = "${chapter.url}";
        document.onkeydown=jumpPage;
    -->
</script>
</#macro>

src/main/webapp/themes/default/pc/search.ftl
<#include "common.ftl"/>

<#macro titleContent>
<title><#if key??>${key?html}的搜索结果<#else>小说搜索</#if>|${getText("label.system.title")}</title>
<meta name="keywords" content="${getText("label.system.siteKeywords")}"/>
<meta name="description" content="${getText("label.system.siteDescription")}" />
</#macro>  

<#macro content>
<div class="mainnav" id="navList">
    <div id="search_ad_01"></div>
    <table class="grid" width="100%" align="center">
    <caption>搜索结果</caption>
      <tr align="center">
        <th width="20%">文章名称</th>
        <th width="40%">最新章节</th>
        <th width="15%">作者</th>
        <th width="9%">字数</th>
        <th width="10%">更新</th>
        <th width="6%">状态</th>
      </tr>
      <#list articleList as article>
      <tr>
        <td class="even"><a href="${article.url}">${article.articlename}</a></td>
        <td class="even"><a href="${article.lastChapterUrl}" target="_blank"> ${article.lastchapter}</a></td>
        <td class="odd"><a href="${encodeURL("/articleList?author=${article.author}")}">${article.author}</a></td>
        <td class="odd">${article.size}</td>
        <td class="odd" align="center">${article.lastupdate?string("MM-dd HH:mm")}</td>
        <td class="even" align="center"><#if article.fullflag?? && article.fullflag >完结<#else>连载中</#if></td>
      </tr>
      </#list>
    </table>
    <div id="search_ad_02"></div>
    <#if key??>
    <div class="pages">
        <div class="pagelink" id="pagelink">
            <#assign listurl = "/search?key=${key?html}&page=">
            <#assign listurlforjs = "${contextPath}/search/${key?html}/" >
            <em id="pagestats">${pagination.pageNumber}/${pagination.totalPages}</em>
            <a href="${encodeURL(listurl +"1")}" class="first">首页</a>
            <#list pagination.pageNumberList as pagenum >
                <#if pagenum_index == 0 && (pagenum > 1 )>
                    <a href="${encodeURL(listurl+ (pagenum-1)?c)}" class="prev">&lt;</a>
                </#if>
                <#if pagenum == pagination.pageNumber>
                    <strong>${pagenum?c}</strong>
                <#else>
                    <a href="${encodeURL(listurl + pagenum?c)}"> ${pagenum?c} </a>
                </#if>
                <#assign mxpagenum = pagenum >
            </#list>
            <#if mxpagenum?? && ( mxpagenum < pagination.totalPages)>
                 <a href="${encodeURL(listurl + (mxpagenum+1)?c)}" class="next">&gt;</a>
            </#if>
            <a href="${encodeURL(listurl + pagination.totalPages?c)}">尾页</a>
            <kbd>
                <input name="page" type="text" size="4" maxlength="6" onkeydown="if(event.keyCode==13){window.location='${listurlforjs}'+this.value+'.html'; return false;}" /></kbd>
        </div>
    </div>
    </#if>
</div>
</#macro>