src/main/java/org/yidu/novel/dto/BookcaseDTO.java
package org.yidu.novel.dto;

import java.util.Date;

import javax.servlet.http.HttpServletResponse;

import org.apache.commons.lang3.StringUtils;
import org.apache.struts2.ServletActionContext;
import org.yidu.novel.action.InfoAction;
import org.yidu.novel.action.ReaderAction;
import org.yidu.novel.constant.YiDuConfig;
import org.yidu.novel.constant.YiDuConstants;
import org.yidu.novel.entity.TBookcase;

/**
 * 
 * <p>
 * 书签DTO
 * </p>
 * Copyright(c) 2014 YiDu-Novel. All rights reserved.
 * 
 * @version 1.1.9
 * @author shinpa.you
 */
public class BookcaseDTO extends TBookcase {
    /**
     * 串行化版本统一标识符
     */
    private static final long serialVersionUID = 2193825089517868949L;
    /**
     * 最新章节编号
     */
    private Integer lastchapterno;
    /**
     * 最新章节名称
     */
    private String lastchapter;
    /**
     * 章节数
     */
    private Integer chapters;
    /**
     * 字数
     */
    private Integer size;
    /**
     * 全本标识
     */
    private Boolean fullflag;
    /**
     * 最后更新时间
     */
    private Date lastupdate;
    /**
     * 图片标识
     */
    private Integer imgflag;

    private String pinyin;

    /**
     * 获取最新章节编号
     * 
     * @return 最新章节编号
     */
    public Integer getLastchapterno() {
        return lastchapterno;
    }

    /**
     * 设定最新章节编号
     * 
     * @param lastchapterno
     *            最新章节编号
     */
    public void setLastchapterno(Integer lastchapterno) {
        this.lastchapterno = lastchapterno;
    }

    /**
     * 获取最新章节名
     * 
     * @return 最新章节名
     */
    public String getLastchapter() {
        return lastchapter;
    }

    /**
     * 设定最新章节名
     * 
     * @param lastchapter
     *            最新章节名
     */
    public void setLastchapter(String lastchapter) {
        this.lastchapter = lastchapter;
    }

    /**
     * 获取 chapters
     * 
     * @return chapters
     */
    public Integer getChapters() {
        return chapters;
    }

    /**
     * 
     * 设置chapters
     * 
     * 
     * @param chapters
     *            chapters
     */
    public void setChapters(Integer chapters) {
        this.chapters = chapters;
    }

    /**
     * 获取 size
     * 
     * @return size
     */
    public Integer getSize() {
        return size;
    }

    /**
     * 
     * 设置size
     * 
     * 
     * @param size
     *            size
     */
    public void setSize(Integer size) {
        this.size = size;
    }

    /**
     * 获取 fullflag
     * 
     * @return fullflag
     */
    public Boolean getFullflag() {
        return fullflag;
    }

    /**
     * 
     * 设置fullflag
     * 
     * 
     * @param fullflag
     *            fullflag
     */
    public void setFullflag(Boolean fullflag) {
        this.fullflag = fullflag;
    }

    /**
     * 获取 lastupdate
     * 
     * @return lastupdate
     */
    public Date getLastupdate() {
        return lastupdate;
    }

    /**
     * 
     * 设置lastupdate
     * 
     * 
     * @param lastupdate
     *            lastupdate
     */
    public void setLastupdate(Date lastupdate) {
        this.lastupdate = lastupdate;
    }

    /**
     * 获取 imgflag
     * 
     * @return imgflag
     */
    public Integer getImgflag() {
        return imgflag;
    }

    /**
     * 
     * 设置imgflag
     * 
     * 
     * @param imgflag
     *            imgflag
     */
    public void setImgflag(Integer imgflag) {
        this.imgflag = imgflag;
    }

    /**
     * 获取pinyin
     * 
     * @return pinyin
     */
    public String getPinyin() {
        return pinyin;
    }

    /**
     * 
     * 设置pinyin
     * 
     * 
     * @param pinyin
     *            pinyin
     */
    public void setPinyin(String pinyin) {
        this.pinyin = pinyin;
    }

    /**
     * 获得图片URL
     * 
     * @return 图片URL
     */
    public String getImgUrl() {
        String fileName = "";
        if (imgflag == null) {
            fileName = "nocover.jpg";
        } else {
            switch (imgflag) {
            case 1:
                fileName = getArticleno() + "s.jpg";
                break;
            case 2:
                fileName = getArticleno() + "s.gif";
                break;
            case 3:
                fileName = getArticleno() + "s.png";
                break;
            case 10:
                fileName = getArticleno() + "l.jpg";
                break;
            default:
                fileName = "nocover.jpg";
                break;
            }
        }
        String imgUrl = YiDuConstants.yiduConf.getString(YiDuConfig.RELATIVE_IAMGE_PATH) + "/";
        if (StringUtils.equals("nocover.jpg", fileName)) {
            imgUrl = imgUrl + fileName;
        } else {
            imgUrl = imgUrl + getArticleno() / YiDuConstants.SUB_DIR_ARTICLES + "/" + getArticleno() + "/" + fileName;
        }
        return imgUrl;
    }

    /**
     * 获取最新章节URL
     * 
     * @return 最新章节URL
     */
    public String getLastChapterUrl() {

        HttpServletResponse response = ServletActionContext.getResponse();
        String url = response.encodeURL(ReaderAction.URL + "?subdir=" + getSubdir() + "&articleno=" + getArticleno()
                + "&chapterno=" + getLastchapterno());

        if (YiDuConstants.yiduConf.getBoolean(YiDuConfig.ENABLE_PINYINURL, false)) {
            url = response.encodeURL(ReaderAction.URL + "?pinyin=" + getPinyin() + "&chapterno=" + getLastchapterno());
        }
        return url;
    }

    /**
     * 获取最新章节URL
     * 
     * @return 最新章节URL
     */
    public String getBookmarkUrl() {

        HttpServletResponse response = ServletActionContext.getResponse();
        String url = response.encodeURL(ReaderAction.URL + "?subdir=" + getSubdir() + "&articleno=" + getArticleno()
                + "&chapterno=" + getChapterno());

        if (YiDuConstants.yiduConf.getBoolean(YiDuConfig.ENABLE_PINYINURL, false)) {
            url = response.encodeURL(ReaderAction.URL + "?pinyin=" + getPinyin() + "&chapterno=" + getChapterno());
        }
        return url;
    }

    /**
     * 获取最新章节URL
     * 
     * @return 最新章节URL
     */
    public String getInfoUrl() {
        HttpServletResponse response = ServletActionContext.getResponse();
        String url = response.encodeURL(InfoAction.URL + "?subdir=" + getSubdir() + "&articleno=" + getArticleno());
        if (YiDuConstants.yiduConf.getBoolean(YiDuConfig.ENABLE_PINYINURL, false)) {
            url = response.encodeURL(InfoAction.URL + "?pinyin=" + getPinyin());
        }
        return url;
    }

}

src/main/java/org/yidu/novel/entity/TArticle.java
package org.yidu.novel.entity;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletResponse;

import org.apache.commons.lang3.StringEscapeUtils;
import org.apache.commons.lang3.StringUtils;
import org.apache.struts2.ServletActionContext;
import org.yidu.novel.action.ArticleListAction;
import org.yidu.novel.action.ChapterListAction;
import org.yidu.novel.action.DownloadAction;
import org.yidu.novel.action.InfoAction;
import org.yidu.novel.action.ReaderAction;
import org.yidu.novel.action.ReviewListAction;
import org.yidu.novel.action.user.BookcaseAction;
import org.yidu.novel.action.user.SubscribeAction;
import org.yidu.novel.action.user.VoteAction;
import org.yidu.novel.cache.CategoryCacheManager;
import org.yidu.novel.cache.SingleBookManager;
import org.yidu.novel.constant.YiDuConfig;
import org.yidu.novel.constant.YiDuConstants;
import org.yidu.novel.dto.TagDTO;
import org.yidu.novel.entity.base.BaseTArticle;
import org.yidu.novel.utils.Utils;

public class TArticle extends BaseTArticle {
    private static final long serialVersionUID = 1L;

    /* [CONSTRUCTOR MARKER BEGIN] */
    public TArticle() {
        super();
    }

    /**
     * Constructor for primary key
     */
    public TArticle(int articleno) {
        super(articleno);
    }

    /* [CONSTRUCTOR MARKER END] */

    public Boolean getFullflag() {
        return isFullflag();
    }

    public Boolean getFirstflag() {
        return isFirstflag();
    }

    public Boolean getAuthorflag() {
        return isAuthorflag();
    }

    public Boolean getDeleteflag() {
        return isDeleteflag();
    }

    public Boolean getUsecustomizeinfotitle() {
        return isUsecustomizeinfotitle();
    }

    public Boolean getUsecustomizelisttitle() {
        return isUsecustomizelisttitle();
    }

    /**
     * 获取HTML格式的小说简介信息
     * 
     * @return HTML格式的小说简介信息
     */
    public String getIntroForHtml() {
        if (getIntro() != null) {
            // 替换换行和空格
            String html = StringEscapeUtils.escapeHtml4(getIntro());
            return html.replaceAll("\r\n", "<br/>").replaceAll("\n", "<br/>").replaceAll("\\s", "&nbsp;");
        }
        return null;
    }

    /**
     * 获得小说简介的缩略
     * 
     * @return 小说简介的缩略
     */
    public String getIntroOmit() {
        if (getIntro() != null && getIntro().length() > 60) {
            return getIntro().substring(0, 60) + "...";
        }
        return getIntro();
    }

    public String getIntroOmit55() {
        if (getIntro() != null && getIntro().length() > 55) {
            return getIntro().substring(0, 55) + "...";
        }
        return getIntro();
    }
    
    public String getIntroOmit30() {
        if (getIntro() != null && getIntro().length() > 30) {
            return getIntro().substring(0, 30) + "...";
        }
        return getIntro();
    }
    
    /**
     * 获得子目录 <br>
     * 默认是小说号/1000
     * 
     * @return 子目录
     */
    public Integer getSubdir() {
        return getArticleno() / YiDuConstants.SUB_DIR_ARTICLES;
    }

    /**
     * 获得最新章节名字的缩略
     * 
     * @return 最新章节名字的缩略
     */
    public String getLastchapterOmit() {
        if (getLastchapter() != null && getLastchapter().length() > 10) {
            return getLastchapter().substring(0, 10);
        }
        return getLastchapter();
    }

    /**
     * 获得最后更新时间
     * 
     * @return 最后更新时间
     */
    public String getLastupdateMin() {
        SimpleDateFormat sdf1 = new SimpleDateFormat("HH:mm:ss");
        return sdf1.format(getLastupdate());
    }

    /**
     * 获得小说类别名字
     * 
     * @return 小说类别名字
     */
    public String getCategoryStr() {
    	return CategoryCacheManager.getCategoryInfoById(String.valueOf(getCategory()));
    }

    /**
     * 获得图片URL
     * 
     * @return 图片URL
     */
    public String getImgUrl() {
        String fileName = "";
        if (getImgflag() == null) {
            fileName = "nocover.jpg";
        } else {
            switch (getImgflag()) {
            case 1:
                fileName = getArticleno() + "s.jpg";
                break;
            case 2:
                fileName = getArticleno() + "s.gif";
                break;
            case 3:
                fileName = getArticleno() + "s.png";
                break;
            case 10:
                fileName = getArticleno() + "l.jpg";
                break;
            default:
                fileName = "nocover.jpg";
                break;
            }
        }
        String imgUrl = YiDuConstants.yiduConf.getString(YiDuConfig.RELATIVE_IAMGE_PATH) + "/";
        if (StringUtils.equals("nocover.jpg", fileName)) {
            imgUrl = imgUrl + fileName;
        } else {
            if (YiDuConstants.yiduConf.getBoolean(YiDuConfig.ENABLE_CLEAN_IMAGE_URL, false)) {
                imgUrl = imgUrl + getArticleno() / YiDuConstants.SUB_DIR_ARTICLES + "-" + getArticleno() + "-"
                        + Utils.convert2MD5(imgUrl + fileName) + fileName;
            } else {
                imgUrl = imgUrl + getArticleno() / YiDuConstants.SUB_DIR_ARTICLES + "/" + getArticleno() + "/"
                        + fileName;
            }
        }
        return imgUrl;
    }

    /**
     * 获取小说介绍页URL
     * 
     * @return 小说介绍页URL
     */
    public String getUrl() {
        HttpServletResponse response = ServletActionContext.getResponse();
        String url = response.encodeURL(InfoAction.URL + "?subdir=" + getSubdir() + "&articleno=" + getArticleno());

        if (YiDuConstants.yiduConf.getBoolean(YiDuConfig.ENABLE_PINYINURL, false)) {
            url = response.encodeURL(InfoAction.URL + "?pinyin=" + getPinyin());
        }
        return url;
    }

    /**
     * 获取作者列表URL
     * 
     * @return 作者列表URL
     */
    public String getAuthorUrl() {
        HttpServletResponse response = ServletActionContext.getResponse();
        return response.encodeURL(ArticleListAction.URL + "?author=" + getAuthor());
    }

    /**
     * 获取分类列表URL
     * 
     * @return 分类列表URL
     */
    public String getCategoryListUrl() {
        HttpServletResponse response = ServletActionContext.getResponse();
        return response.encodeURL(ArticleListAction.URL + "?category=" + getCategory());
    }

    /**
     * 获取最新章节URL
     * 
     * @return 最新章节URL
     */
    public String getLastChapterUrl() {
        HttpServletResponse response = ServletActionContext.getResponse();
        String url = response.encodeURL(ReaderAction.URL + "?subdir=" + getSubdir() + "&articleno=" + getArticleno()
                + "&chapterno=" + getLastchapterno());

        if (YiDuConstants.yiduConf.getBoolean(YiDuConfig.ENABLE_PINYINURL, false)) {
            url = response.encodeURL(ReaderAction.URL + "?pinyin=" + getPinyin() + "&chapterno=" + getLastchapterno());
        }
        return url;
    }

    /**
     * 获取最新章节URL
     * 
     * @return 最新章节URL
     */
    public String getThumbnailLastChapterUrl() {
        HttpServletResponse response = ServletActionContext.getResponse();
        return response.encodeURL(ReaderAction.URL + "?chapterno=" + getLastchapterno());
    }

    /**
     * 获取加入书签URL
     * 
     * @return 加入书签URL
     */
    public String getAddBookcaseUrl() {
        HttpServletResponse response = ServletActionContext.getResponse();
        return response.encodeURL(BookcaseAction.URL + "!add?articleno=" + getArticleno());
    }

    /**
     * 获取推荐小说URL
     * 
     * @return 推荐小说URL
     */
    public String getAddVoteUrl() {
        HttpServletResponse response = ServletActionContext.getResponse();
        return response.encodeURL(VoteAction.URL + "?articleno=" + getArticleno());
    }

    /**
     * 获取下载小说URL
     * 
     * @return 下载小说URL
     */
    public String getDownloadUrl() {
        HttpServletResponse response = ServletActionContext.getResponse();
        return response.encodeURL(DownloadAction.URL + "?subdir=" + getSubdir() + "&articleno=" + getArticleno());
    }

    /**
     * 获取小说评价URL
     * 
     * @return 小说评价URL
     */
    public String getReviewUrl() {
        HttpServletResponse response = ServletActionContext.getResponse();
        return response.encodeURL(ReviewListAction.URL + "?subdir=" + getSubdir() + "&articleno=" + getArticleno());
    }

    /**
     * 获取章节列表URL
     * 
     * @return 分类列表URL
     */
    public String getChapterListUrl() {
        HttpServletResponse response = ServletActionContext.getResponse();
        String url = response.encodeURL(ChapterListAction.URL + "?subdir=" + getSubdir() + "&articleno="
                + getArticleno());

        if (YiDuConstants.yiduConf.getBoolean(YiDuConfig.ENABLE_PINYINURL, false)) {
            url = response.encodeURL(ChapterListAction.URL + "?pinyin=" + getPinyin());
        }
        return url;
    }

    /**
     * 获取订阅URL
     * 
     * @return 订阅URL
     */
    public String getSubscribeUrl() {
        HttpServletResponse response = ServletActionContext.getResponse();
        return response.encodeURL(SubscribeAction.URL + "!add?articleno=" + getArticleno());
    }

    /**
     * 获取小说介绍页拼音形式的URL
     * 
     * @return 小说介绍页拼音形式的URL
     */
    public String getSingleBookUrl() {
        String pinyin = SingleBookManager.getPinYinHeadChar(getArticleno());
        if (StringUtils.isNotBlank(pinyin)) {
            return "http://" + pinyin + "." + YiDuConstants.yiduConf.getString(YiDuConfig.ROOT_DOMAIN);
        } else {
            return YiDuConstants.yiduConf.getString(YiDuConfig.ROOT_DOMAIN);
        }
    }

    /**
     * 获取小说tag的URL
     * 
     * @return 小说介绍页拼音形式的URL
     */

src/main/webapp/themes/default/single/error.ftl
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" >
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>错误页面</title>
    <meta name="keywords" content="错误页面" />
    <meta name="description" content="出错了，请重新选择!" />
    <link href="${contextPath}/themes/${themeName}/single/css/StyleSheet.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div class="lbox">
    <div class="section">
        <p class="b-all-switch normal">出现错误啦！</p>
        <div class="msgwin mgl_61" style="text-align:center;">
            <div class="blockcontent">
                <div style="padding:10px"><br />
            <@s.actionerror /><br />请&nbsp;<a href="javascript:history.back(1)">返 回</a>&nbsp;并修正或&nbsp;<a href="${contextPath}/">返回首页</a><br /><br /></div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

src/main/webapp/themes/default/single/info.ftl
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" >
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>${article.articlename}|${article.articlename}最新章节|${article.articlename}TXT下载|${article.articlename}单本阅读</title>
	<meta name="keywords" content="${article.articlename}，${article.articlename}单本，${article.articlename}最新章节，${article.articlename}TXT下载，${article.author}的小说" />
	<meta name="description" content="《${article.articlename}》是由${article.author}所写的一部情节跌宕起伏、扣人心弦的${article.categoryStr}小说，本站免费提供最新的清爽干净的文字章节在线阅读!" />
	<meta name="copyright" content="${article.articlename}版权属于作者：${article.author}" />
	<link href="${contextPath}/themes/${themeName}/single/css/StyleSheet.css" rel="stylesheet" type="text/css" /></head>
	<!--360结构化-->
	<meta property="og:type" content="novel"/>
	<meta property="og:title" content="${article.articlename?html}"/>
	<meta property="og:description" content="<#if (article.intro ?length != 0)>${article.intro?html}<#else>暂无简介</#if>"/>
	<meta property="og:image" content="${article.imgUrl}"/>
	<meta property="og:novel:category" content=${article.categoryStr}"/>
	<meta property="og:novel:author" content="${article.author?html}"/>
	<meta property="og:novel:book_name" content="${article.articlename?html}"/>
	<meta property="og:novel:read_url" content="${article.url}"/>
	<!--选填-->
	<meta property="og:novel:status" content="<#if article.fullflag>完结<#else>连载中</#if>"/>
	<meta property="og:novel:update_time" content="${article.lastupdate?string("yyyy-MM-dd HH:mm")}"/>
	<meta property="og:novel:click_cnt" content="${article.allvisit?c}"/>
	<meta property="og:novel:latest_chapter_name" content="${article.lastchapter}"/>
	<meta property="og:novel:latest_chapter_url" content="${article.lastChapterUrl}"/>
<body>
<div class="head">
	<div class="padding">
		<div class="header">
			<ul class="menu">
				<li class="on"><a href="${contextPath}/" title="${article.articlename}">${article.articlename}</a></li>
				<li style='color:#FFF;padding-left:20px;'>《${article.articlename}》是由${article.author}所写的一部情节跌宕起伏、扣人心弦的${article.categoryStr}经典小说！</li>
			</ul>
		</div>
	</div>
</div>
<div class="lbox">
	<div class="section">
		<div class="book_info">
			<div class="pic">
				<a href="/"><img alt="${article.articlename}" src="${article.imgUrl}" style="width: 120px;height: 150px;" /></a>
			</div>
			<h1 style="width:200px;"><a href="/">${article.articlename}</a></h1>
			<span style="float:left;">
                <!-- 将此标记放在您希望显示like按钮的位置 -->
                <div class="bdlikebutton"></div>
                <!-- 将此代码放在适当的位置，建议在body结束前 -->
                <script id="bdlike_shell"></script>
                <script>
                var bdShare_config = {
                    "type":"large",
                    "color":"red",
                    "uid":"681543",
                    "likeText":"支持 ${article.articlename}",
                    "likedText":"您已经顶过谢谢"
                };
                document.getElementById("bdlike_shell").src="http://bdimg.share.baidu.com/static/js/like_shell.js?t=" + Math.ceil(new Date()/3600000);
                </script>
            </span>
            <div class="infos">
                <span><h3> 
                </h3></span>
            </div>
            <div class="upd">
                    最新章节： <a href="${article.thumbnailLastChapterUrl}" title="${article.lastchapter}">${article.lastchapter}</a>&nbsp;&nbsp;&nbsp;&nbsp;${article.lastupdate?string("yyyy-MM-dd HH:mm")}
            </div>
            <p><a href="${article.thumbnailLastChapterUrl}" title="${article.lastchapter}">《${article.articlename}》是由${article.author}所写的一部情节跌宕起伏、扣人心弦的${article.categoryStr}小说， ${article.lastchapter} 是小说《${article.articlename}》的最新章节。</a></p>
        </div>
    </div>
    <div class="lbox" style="background:#FFFFFF;">
        <p style="text-align:center;padding:10px;">
            <span style="font-size:26px;color:green;padding:10px;">${article.articlename}-${article.author}</span></p>
        <p style="text-align:left;color:green;padding:10px;">
            ${article.intro?html}</p> 
        <p style="text-align:left;color:green;padding:10px;">
            &nbsp;&nbsp;为方便您下次继续访问，请使用<span style="color:red;">Ctrl+D</span>快捷键收藏本站！ ^_^</p>
    </div>
    <div class="book_list">
        <h2>${article.articlename}最新章节</h2>
            <ul>
            <#list chapterList as chapter>
                <li><a href="${chapter.thumbnailUrl}" title="${chapter.chaptername}">${chapter.chaptername}</a></li>
            </#list>
            </ul>
    </div>
</div>
<div class="head2">
<div class="padding">
<div class="header">
<ul class="menu">
<li class="on"><a href="/" title="${article.articlename}">${article.articlename}</a></li>
<li style="color:#FFF;padding-left:20px;">喜欢《${article.articlename}》的书迷们，请记住本站http://${singleBookServerName}丫，这里绝对是你阅读的首选！</li>
</ul>
</div>
</div>
</div>
<div class="links">
    <h5>友情链接</h5>
    <ul>
        <li><a href='http://www.51yd.org' target='_blank' title="易读小说系统">易读小说系统</a> </li>
    </ul>
</div>
<div class="foot">
    <p>本站提供的《${article.articlename}》，是由${article.author}所写的一部情节跌宕起伏、扣人心弦的${article.categoryStr}小说。《${article.articlename}》版权属于${article.author}，从网络收集只为更多的书迷们欣赏!<br>${getText("label.system.support")}</p>
    <script>window._bd_share_config={"common":{"bdSnsKey":{},"bdText":"","bdMini":"1","bdMiniList":false,"bdPic":"","bdStyle":"0","bdSize":"16"},"slide":{"type":"slide","bdImg":"3","bdPos":"right","bdTop":"100"},"image":{"viewList":["tieba","qzone","sqq","tsina","weixin"],"viewText":"分享到：","viewSize":"16"},"selectShare":{"bdContainerClass":null,"bdSelectMiniList":["tieba","qzone","sqq","tsina","weixin"]}};with(document)0[(getElementsByTagName('head')[0]||body).appendChild(createElement('script')).src='http://bdimg.share.baidu.com/static/api/js/share.js?v=89860593.js?cdnversion='+~(-new Date()/36e5)];</script>
</div>
</body>
</html>